### ISSUE TITLE
GPU issues in training

### ISSUE THREAD

**Issue by sakai5678** [ifzhang/ByteTrack#401]
When I run the code below, an error occurs.
Is it not possible to train with one GPU?

cd <ByteTrack_HOME>
python3 tools/train.py -f exps/example/mot/yolox_x_ablation.py -d 8 -b 48 --fp16 -o -c pretrained/yolox_x.pth

[error]
Traceback (most recent call last):
  File "tools/train.py", line 112, in <module>
	assert num_gpu <= torch.cuda.device_count()
AssertionError

**Comment by m-peker** [comment]
The error you are encountering is because the number of GPUs specified (-d 8) exceeds the available GPUs on your machine. The -d parameter indicates the number of GPUs to use for training. If you want to train with only one GPU, you should set this parameter to 1.

Here is how you can modify your command to use only one GPU:

bash

cd <ByteTrack_HOME>
python3 tools/train.py -f exps/example/mot/yolox_x_ablation.py -d 1 -b 6 --fp16 -o -c pretrained/yolox_x.pth
Additionally, you should adjust the batch size (-b) accordingly to fit into the memory of a single GPU. In this example, I reduced it from 48 to 6, but you might need to experiment with this value based on the GPU memory capacity available on your system.

If you continue to encounter issues, you can also check and modify the tools/train.py script to ensure it properly handles the number of GPUs specified. The relevant section of the code is:

python

num_gpu = torch.cuda.device_count()
assert num_gpu >= 1, "No GPUs available for training"
By ensuring that the script properly identifies and utilizes the available GPU(s), you can avoid such errors.

**Comment by sakai5678** [comment]
解決できました。ありがとうございました！
