### ISSUE TITLE
run ByteTrack with yolov5 instead of yolox

### ISSUE THREAD

**Issue by tungdop2** [ifzhang/ByteTrack#99]
how I can run train.py with yolov5 pretrained weights from its model zoo instead of yolox?

**Comment by gmt710** [comment]
Hi, any process?

**Comment by tungdop2** [comment]
> 

Yes, I load yolo5s from torch hub and put its detection to ByteTrack update function, seems it works.

**Comment by gmt710** [comment]
@tungdop2 , I submitted a PR.  https://github.com/ifzhang/ByteTrack/pull/101

**Comment by gmt710** [comment]
--ckpt
&nbsp;

Best wishes,
Mengting Gu.


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月6日(星期一) 晚上8:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ifzhang/ByteTrack] run ByteTrack with yolov5 instead of yolox (Issue #99)





 
@gmt710 thank you so much.
 But how to pt yolov5s into a folder and load it, instead of attemp_load in your init
 def init_det(weights): # Load model model = attempt_load(weights, map_location=device)  # load FP32 model # model = torch.load(weights, map_location=device)[ #     'model'].float()  # load to FP32 model.to(device).eval() return model
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gmt710** [comment]
this can load the weight from the folder.

**Comment by tungdop2** [comment]
@gmt710 oh sorry, you pass attemp_download

**Comment by gmt710** [comment]
okay, you can comment it -- attemp_download.

**Comment by gmt710** [comment]
What command ?  My yolov5s is v4.

**Comment by gmt710** [comment]
https://github.com/ultralytics/yolov5/issues/5175, you can refer this, okay?

**Comment by tungdop2** [comment]
@gmt710 yeah I fix it by using the latest yolov5 version, but now I get new problems:
1. I try 2 versions, 1 is your way
`model = init_det(args.ckpt)`
and 1 is use torch.hub
`model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)`
The second way run much faster, why?
2. I run code in MOT17 datasets, the result is always bad in the first folder (MOT17-02-FRCNN), but it becomes better from the following folders.

I'm not sure about these 2 problems, can you explain why? You can check my clone [here](https://github.com/tungdop2/ByteTrack_clone), which I modify your code a little bit.

**Comment by gmt710** [comment]
Haha, I don't clearly know about this.
Can my pr code work fine ?
If I am free, I'll check, ok?

**Comment by tungdop2** [comment]
Thank you, your code work, help me a lot, and I change it to version 6. The problem is, I think the model needs to warm up. Do you know how to do this?

**Comment by gmt710** [comment]
you can search the difference between torch.load and torch.hub.load ?

**Comment by tungdop2** [comment]
@gmt710 got a minute? I try at MOT17 with [these weights](https://drive.google.com/file/d/1gglIwqxaH2iTvy6lZlXuAcMpd_U0GCUb/view), but the result is so bad? I really don't know why, because the detections seem to work well.

**Comment by gmt710** [comment]
@tungdop2 
Can you show your detect result and track result?

**Comment by gmt710** [comment]
@tungdop2 , Okay, Next I will check this. Thanks.

**Comment by gmt710** [comment]
@tungdop2 I‘ve checked, I think maybe you need check my code, ok? your setting and inference code is not the same as me.
My result can track normally, but not good as the author's result. The authot train the model on MOT pedes datasets, but I use the pretrained model on voc datasets.

**Comment by nguyencongphuchust** [comment]
Hi all, I completed run byte track with yolov5 in python. I want to deploy (byte track + yolov5) in tensorrt. I convert yolov5 to tensorrt from guide of repo yolov5 to get file .engine. After that, I update shape input in bytetrack.cpp same with input my model (640, 640). And I build and run follow guide, replace path yolox.engine file to my yolov5s.engine file. But I get error "[pluginV2Runner.cpp::load::290] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)"
I also do follow your guide, used torch2trt to convert my weight yolov5s to tensorrt, by I also get error: assert dtype == t.dtype  # , 'Tensor data types must match'). Inspite I set shape inout model correct with my model.
I really don't know why. Do you know how to fix this? Thanks you!

Error when I deploy with my file engine yolov5 (I convert follow guide repo yolov5):
![image](https://user-images.githubusercontent.com/44407788/146479331-ba9c0edc-ee75-47fc-b8cc-5c35d7b98d7d.png)
 
Error when I conver yolov5 by torch2trt:
![image](https://user-images.githubusercontent.com/44407788/146479437-87745957-341c-4ad0-a4d9-38f7b7fb03b2.png)

**Comment by nemonameless** [comment]
@gmt710  Any results about yolov5-bytetracker MOTA of MOT17 dataset?

**Comment by gmt710** [comment]
you need train a model for pedetrian detection.

**Comment by gmt710** [comment]
you need train pedetrian datasets.

**Comment by nemonameless** [comment]
> @nemonameless yeah, you can check it here https://github.com/tungdop2/ByteTrack_clone. The result with these weights https://drive.google.com/file/d/1gglIwqxaH2iTvy6lZlXuAcMpd_U0GCUb/view is worse than yolox. Demo MOT17 here https://drive.google.com/drive/folders/15zMB-ouIQwI3hYKIm-co-uqgmAYFQEjh?usp=sharing

so where is your results of  yolov5-bytetracker ???

**Comment by tungdop2** [comment]
@nemonameless  here https://drive.google.com/drive/u/1/folders/1kYx9ZoCTTPuthYKoy1ZT-INPowpldOiX

**Comment by NguyenCongPhucBKHN** [comment]
Have any one deploy bytetrack with yolov5 in tensorrt ?

**Comment by hyeonmin11** [comment]
> [ultralytics/yolov5#5175](https://github.com/ultralytics/yolov5/issues/5175), you can refer this, okay?

Hi I have question about your yolov5-bytetracker code.
To train custom data with your yolov5-bytetracker code, What my dataset format should be? Yolo or CoCo format?
Thanks.

**Comment by hyeonmin11** [comment]
@gmt710 
Hi I have question about your yolov5-bytetracker code.
To train custom data with your yolov5-bytetracker code, What my dataset format should be? Yolo or CoCo format?
Thanks.

**Comment by gmt710** [comment]
yolo is ok, you can refer my blog.

**Comment by hyeonmin11** [comment]
@gmt710 
Glad to see your blog.. but I can't read chinese. Are there major changes from original ByteTrack(yolox bytetrack)? e.g hyp..
https://github.com/ifzhang/ByteTrack/issues/5
In this issue, Tetsujinfr  tuned low boundary confidence score to fit other detector, and also did sth many as you can see in last comment.
Did you also do those kinds of editing process to run ByteTrack with yolov5?

**Comment by gmt710** [comment]
@hyeonmin11 , If you want to train yolov5-bytetrack, you only need to train yolov5 on your own datasets. The blog include the steps. if you can find any other blog for yolov5 training, it is suitable for you.

I revised a few places that are difficult to explain in a few sentences.

**Comment by NeoYY** [comment]
@gmt710

I have a couple of questions after I read your code... If you can help me to figure these out that will be nice.
Is it true that the training for the original repo and your repo is actually training the YOLO detection model instead of the detector + tracker?
So you haven't really changed anything for the training process because you are assuming the yolov5 weights are pretrained based on the MOT dataset?
In such a circumstance can we draw a conclusion that we don't need to train the tracker at all?

Thanks!

**Comment by gmt710** [comment]
yes, you only need train yolov5 on your detection datasets.

**Comment by Camilochiang** [comment]
Hei @gmt710 . Which Speed did you reach using YOLOv5 and your implementation? Also, in which hardware?

**Comment by gmt710** [comment]
I haven't tested the speed . you can test it yourself.

**Comment by moonsh** [comment]
@gmt710  Just wonder any reason for training Yolov5 instead YoloX ?

**Comment by NeoYY** [comment]
> @gmt710  Just wonder any reason for training Yolov5 instead YoloX ?  

Yolov5s can provide a faster runtime speed.

**Comment by moonsh** [comment]
@NeoYY  I see. But Yolox provides higher accuracy than Yolov5 ?

**Comment by NeoYY** [comment]
> @NeoYY  I see. But Yolox provides higher accuracy than Yolov5 ?

That's right, since the performance of tracker heavily relying on detector. And as we know YoloX is much better than yolo5.

**Comment by harryc7** [comment]
how can i solve this error？
AttributeError: 'collections.OrderedDict' object has no attribute 'float'

**Comment by mikel-brostrom** [comment]
Here you have a Yolov5+ByteTrack implementation:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet
